Cgit fix
underground-software/orbit pull request #74
Opened 2024-02-27 19:44 UTC by michael-burke4

See syzygy cgit pull request

2024-03-01 19:47 UTC, charliemirabile requested changes

2024-03-01 19:47 UTC, charliemirabile commented on cgitrc
> +include=/etc/cgitrc.repos
should probably add an example cgitrc.repos to this repo (maybe even one that just includes the scan-path line that was removed from the example cgitrc) and modify the example compose files in this repo to mount it into /etc/cgitrc.repos. I think it is important to keep these containers able to operate separably.

2024-03-01 19:47 UTC, charliemirabile commented on radius.py
> +    if (re.search("^/[\w\-\.]+/plain(/|$)", cgit_env['PATH_INFO'])):
I don't love this regex. Hard to read (imo) and I can't help but worry about edge cases (what if you had a repo named `plain` or something stupid). I think maybe just hiding the button is enough. Until we actually fix the plain feature, if you go to a url that isn't linked anywhere and it crashes I think that that is acceptable (especially given that we handle those errors more elegantly in the follow up commit).

2024-03-01 19:47 UTC, charliemirabile commented on radius.py
> +    try:
maybe prefer str.find to str.index with try catch

2024-03-13 02:28 UTC, theyoyojo commented
Re-open this on [singularity](https://github.com/underground-software/singularity)

2024-03-13 02:28 UTC, closed without merging